
package cc.mrbird.febs.webService.his;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebCommonService", targetNamespace = "http://webservice.common.ld.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebCommonService {


    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doThridService", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.DoThridService")
    @ResponseWrapper(localName = "doThridServiceResponse", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.DoThridServiceResponse")
    public String doThridService(
        @WebParam(name = "params", targetNamespace = "")
        String params);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSuc", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.IsSuc")
    @ResponseWrapper(localName = "isSucResponse", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.IsSucResponse")
    public boolean isSuc(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param params
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doWebCommonService", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.DoWebCommonService")
    @ResponseWrapper(localName = "doWebCommonServiceResponse", targetNamespace = "http://webservice.common.ld.com/", className = "cc.mrbird.febs.webService.his.DoWebCommonServiceResponse")
    public String doWebCommonService(
        @WebParam(name = "params", targetNamespace = "")
        String params);

}
