
package cc.mrbird.febs.webService.his;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebCommonServiceImplService", targetNamespace = "http://webservice.common.ld.com/", wsdlLocation = "http://192.168.60.208:9081/his/service/ws?wsdl")
public class WebCommonServiceImplService
    extends Service
{

    private final static URL WEBCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBCOMMONSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName WEBCOMMONSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.common.ld.com/", "WebCommonServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.60.208:9081/his/service/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        WEBCOMMONSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public WebCommonServiceImplService() {
        super(__getWsdlLocation(), WEBCOMMONSERVICEIMPLSERVICE_QNAME);
    }

    public WebCommonServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBCOMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public WebCommonServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBCOMMONSERVICEIMPLSERVICE_QNAME);
    }

    public WebCommonServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBCOMMONSERVICEIMPLSERVICE_QNAME, features);
    }

    public WebCommonServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebCommonServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebCommonService
     */
    @WebEndpoint(name = "WebCommonServiceImplPort")
    public WebCommonService getWebCommonServiceImplPort() {
        return super.getPort(new QName("http://webservice.common.ld.com/", "WebCommonServiceImplPort"), WebCommonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebCommonService
     */
    @WebEndpoint(name = "WebCommonServiceImplPort")
    public WebCommonService getWebCommonServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.common.ld.com/", "WebCommonServiceImplPort"), WebCommonService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBCOMMONSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBCOMMONSERVICEIMPLSERVICE_EXCEPTION;
        }
        return WEBCOMMONSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
